const { app, BrowserWindow } = require('electron');
const path = require('node:path');
app.setPath('userData', path.join(__dirname, '.smoke-data'));
require('./main.cjs');
app.on('browser-window-created', (_event, win) => {
  win.hide();
  win.webContents.once('did-finish-load', async () => {
    try {
      const result = await win.webContents.executeJavaScript(`(async () => {
        while (!loaded) await new Promise(r => setTimeout(r, 20));
        const testBook = await window.writer.create('测试作品甲'); await openBook(testBook.id);
        renderDraft({ text: '第一章 起点\\n第一节 清晨\\n正文内容' });
        if (blocks().length !== 3 || blocks().some(p => p.dataset.type !== 'body')) throw new Error('Legacy migration failed');
        const first = blocks()[0]; placeButton(first); button.click();
        menu.querySelector('[data-type="chapter"]').click();
        placeButton(blocks()[1]); button.click(); menu.querySelector('[data-type="section"]').click();
        if (list.children.length !== 2 || !list.children[1].classList.contains('section')) throw new Error('Outline failed');
        list.children[1].click();
        if (currentParagraph() !== blocks()[1]) throw new Error('Navigation failed');
        toggle.click(); if (!document.body.classList.contains('drawer-open') || drawer.inert) throw new Error('Drawer failed');
        toggle.click(); if (!drawer.inert) throw new Error('Drawer close failed');
        slider.value = 26; applySize(); changed(); await save();
        const draft = await window.writer.load();
        if (draft.paragraphs[0].type !== 'chapter' || draft.paragraphs[1].type !== 'section' || draft.fontSize !== 26) throw new Error('Persistence mismatch');
        renderDraft(draft); if (list.children.length !== 2 || paragraphText(blocks()[2]) !== '正文内容') throw new Error('Reload failed');
        editor.focus(); const range = document.createRange(); range.selectNodeContents(blocks()[0]); range.collapse(false); const selection = window.getSelection(); selection.removeAllRanges(); selection.addRange(range);
        document.execCommand('insertParagraph'); normalize();
        if (blocks()[1].dataset.type !== 'body' || blocks()[0].dataset.type !== 'chapter') throw new Error('Enter type inheritance failed');
        renderDraft({ text: '' }); editor.focus(); document.execCommand('selectAll'); document.execCommand('insertText', false, '第一段\\n第二段\\n\\n第四段'); normalize();
        if (snapshot().text !== '第一段\\n第二段\\n\\n第四段') throw new Error('Multiline plain text failed: ' + snapshot().text);
        renderDraft(draft); toggle.click();
        const beforeHome = snapshot().text;
        homeButton.click(); while (homePage.hidden) await new Promise(r => setTimeout(r, 20));
        if (!workspace.hidden || !toggle.hidden) throw new Error('Home navigation failed');
        await openBook(testBook.id);
        if (workspace.hidden || !homePage.hidden || snapshot().text !== beforeHome || list.children.length !== 2) throw new Error('Continue writing failed');
        homeButton.click(); while (homePage.hidden) await new Promise(r => setTimeout(r, 20));
        const titleForm = Array.from(bookList.querySelectorAll('form')).find(f => f.querySelector('input').value === '测试作品甲');
        if (titleForm.querySelector('button')) throw new Error('Unexpected title save button');
        titleForm.querySelector('input').value = '新书名'; titleForm.querySelector('input').dispatchEvent(new Event('input'));
        await new Promise(r => setTimeout(r, 800));
        if ((await window.writer.load(testBook.id)).title !== '新书名') throw new Error('Automatic title save failed');
        await openBook(testBook.id); if (bookTitle.textContent !== '新书名') throw new Error('Rename failed');
        const second = await window.writer.create('测试作品乙'); await openBook(second.id);
        if (snapshot().text !== '' || list.children.length) throw new Error('Books not isolated');
        renderDraft({ text: '第二部作品的内容' }); changed(); await save();
        await openBook(testBook.id); if (snapshot().text !== beforeHome || list.children.length !== 2) throw new Error('First book corrupted');
        await openBook(second.id); if (snapshot().text !== '第二部作品的内容') throw new Error('Second book persistence failed');
        homeButton.click(); while (homePage.hidden) await new Promise(r => setTimeout(r, 20));
        const count = (await window.writer.list()).books.length;
        document.getElementById('new-book-button').click();
        while (bookList.querySelectorAll('.book-card').length !== count + 1) await new Promise(r => setTimeout(r, 20));
        await new Promise(r => setTimeout(r, 50));
        if (document.activeElement.tagName !== 'INPUT' || document.activeElement.value !== '未命名作品') throw new Error('Plus creation failed');
        if (getComputedStyle(bookList).gridTemplateColumns.split(' ').length < 2) throw new Error('Grid layout failed');
        return { persisted: true, migration: true, outline: true, navigation: true, drawer: true, enter: true, home: true, rename: true, isolatedBooks: true, plus: true, grid: true };
      })()`);
      console.log(JSON.stringify(result));
      await require('node:fs/promises').writeFile(path.join(__dirname, '.smoke-data/result.json'), JSON.stringify(result));
      win.showInactive();
      await new Promise(resolve => setTimeout(resolve, 350));
      await require('node:fs/promises').writeFile(path.join(__dirname, '.smoke-data/chapters.png'), (await win.webContents.capturePage()).toPNG());
      app.exit(0);
    } catch (error) { console.error(error); await require('node:fs/promises').writeFile(path.join(__dirname, '.smoke-data/result.json'), JSON.stringify({ error: String(error) })); app.exit(1); }
  });
});
setTimeout(() => { console.error('Startup timed out'); app.exit(1); }, 15000);
